-- ESTADOCONTRATACION
drop table if exists t_estado_contratacion;
create table estado_contratacion (cod_estado_contratacion varchar(255), descripcion varchar(255));

-- OPERACIONESCONTRATACION
drop table if exists t_operaciones_contratacion;
create table operaciones_contratacion (cod_operaciones_contratacion varchar(255), descripcion varchar(255));

-- FONDOSCLIENTE
drop table if exists t_fondos_cliente;
create table fondos_cliente (id_fondos_cliente bigint generated by default as identity
cod_isin varchar(255) not null,
id_clientes bigint,
fecha_contratacion date not null);

-- FONDOS-CLIENTE-HISTORY
drop table if exists t_fondos_cliente_history;
create fondos_cliente_history (id_fondos_cliente bigint,
estado_contratacion varchar(255),
fecha_cambio_estado date,
importe double);