-- ESTADOSCONTRATACION
drop table if exists t_estados_contratacion;
create table t_estados_contratacion (
id_estados_contratacion bigint,
descripcion varchar(255));

-- FONDOSCLIENTE
drop table if exists t_fondos_cliente;
create table t_fondos_cliente (
id_fondos_cliente bigint generated by default as identity
cod_isin varchar(255) not null,
id_clientes bigint,
fecha_contratacion date not null);

-- FONDOSCLIENTEHISTORY
drop table if exists t_fondos_cliente_history;
create t_fondos_cliente_history (
id_fondos_cliente bigint,
estados_contratacion varchar(255),
fecha_cambio_estado date,
operaciones_contratacion varchar(255),
importe double);


-- OPERACIONESCONTRATACION
drop table if exists t_operaciones_contratacion;
create table t_operaciones_contratacion (
id_operaciones_contratacion bigint,
descripcion varchar(255));