-- CLIENTES
drop table if exists clientes;
create table clientes (id bigint generated by default as identity, nombre varchar(255) not null, apellido varchar(255) not null, email varchar(255) not null, born_at varchar(255) not null , foto null, create_at timestamp);